name: Crunch-Battle-Utils
main: com.crunch.battleutils.Core
version: 1.0
api-version: 1.20
commands:
  battle:
    description: Toggle battle mode
    usage: /battle on <deaths> or /battle off
permissions:
  battle.toggle:
    description: Toggles the battle utils on
    default: op